export const STATUS_CODE = {
  SUCCESS: 1000,
  COMMON_ERROR: 1001,
  NOT_LOGIN: 1002,
  PERMISSION_DENIED: 1003,
};

export const HTTP_STATUS_CODE = {
  SUCCESS: 200,
  NOT_FOUND: 404,
  ERROR: 500,
};

// 错误状态码
export enum ERR_CODE {
  SYSTEM_ERROR = 'SYSTEM_ERROR',
  DATA_ERROR = 'DATA_ERROR',
  INCOMPLETE_DELETE = 'INCOMPLETE_DELETE',
  TRANSACTIONAL_ERROR = 'TRANSACTIONAL_ERROR',
  NO_THIS_DATA = 'NO_THIS_DATA',
  DATA_EXIST = 'DATA_EXIST',
  VERIFICATION_EXPIRED = 'VERIFICATION_EXPIRED',
  VERIFICATION_NOT_MATCHED = 'VERIFICATION_NOT_MATCHED',
  PASSWORD_NOT_MATCHED = 'PASSWORD_NOT_MATCHED',
  LOGIN_EXPIRED = 'LOGIN_EXPIRED',
  IDENTITY_MATCH_FAIL = 'IDENTITY_MATCH_FAIL',
  PERMISSION_DENIED = 'PERMISSION_DENIED',
}

export const LANGS = {
  'zh-CN': '简体中文',
  'zh-TW': '繁體中文',
  'en-US': 'English',
  'ja-JP': '日本語',
  'ko-KR': '한국어'
};
