import {
  Button, Typography,
  Divider, Row, Col, Layout, Space,
  Affix, Breadcrumb, Dropdown, Menu, PageHeader, Pagination, Steps,
  AutoComplete, Cascader, Checkbox, DatePicker, Input, InputNumber, Radio, Rate, Select, Slider, Switch, TimePicker, Transfer, TreeSelect, Upload,
  Avatar, Badge, Calendar, Card, Carousel, Collapse, Comment, Descriptions, Empty, Image, List, Popover, Statistic, Table, Tabs, Tag, Timeline, Tooltip, Tree,
  Alert, Drawer, message, Modal, notification, Popconfirm, Progress, Result, Skeleton, Spin,
  Anchor, BackTop
} from 'antd';

export default {
  // 通用
  Button,
  Title: Typography.Title,
  Paragraph: Typography.Paragraph,
  Text: Typography.Text,
  Link: Typography.Link,

  // 布局
  Divider,
  Row,
  Col,
  Layout,
  LayoutHeader: Layout.Header,
  LayoutFooter: Layout.Footer,
  LayoutSider: Layout.Sider,
  LayoutContent: Layout.Content,
  Space,

  // 导航
  Affix,
  Breadcrumb,
  BreadcrumbItem: Breadcrumb.Item,
  BreadcrumbSeparator: Breadcrumb.Separator,
  Dropdown,
  Menu,
  MenuItem: Menu.Item,
  MenuItemGroup: Menu.ItemGroup,
  SubMenu: Menu.SubMenu,
  PageHeader,
  Pagination,
  Steps,
  StepsStep: Steps.Step,

  // 输入
  AutoComplete,
  Cascader,
  Checkbox,
  CheckboxGroup: Checkbox.Group,
  DatePicker,
  Input,
  InputNumber,
  Radio,
  RadioGroup: Radio.Group,
  Rate,
  Select,
  SelectOption: Select.Option,
  SelectOptGroup: Select.OptGroup,
  Slider,
  Switch,
  TimePicker,
  Transfer,
  TreeSelect,
  TreeNode: TreeSelect.TreeNode,
  Upload,

  // 数据展示
  Avatar,
  Badge,
  Calendar,
  Card,
  Carousel,
  Collapse,
  CollapsePanel: Collapse.Panel,
  Comment,
  Descriptions,
  DescriptionsItem: Descriptions.Item,
  Empty,
  Image,
  List,
  ListItem: List.Item,
  Popover,
  Statistic,
  StatisticCountdown: Statistic.Countdown,
  Table,
  Tabs,
  TabPane: Tabs.TabPane,
  Tag,
  Timeline,
  TimelineItem: Timeline.Item,
  Tooltip,
  Tree,

  // 反馈
  Alert,
  Drawer,
  message,
  Modal,
  notification,
  Popconfirm,
  Progress,
  Result,
  Skeleton,
  SkeletonAvatar: Skeleton.Avatar,
  SkeletonButton: Skeleton.Button,
  SkeletonImage: Skeleton.Image,
  SkeletonInput: Skeleton.Input,
  Spin,

  // 其它
  Anchor,
  BackTop
};

