import {
  Line, Area, Column, Bar, Pie, DualAxes, Gauge, Liquid, Bullet, Scatter, Rose, OrganizationTreeGraph, IndentedTree, DagreGraph, DagreFundFlowGraph, Sankey, Chord, Heatmap, TinyLine, TinyArea, TinyColumn, Progress as ChartsProgress, RingProgress, Radar, Treemap, Funnel, Waterfall, WordCloud, Histogram, Sunburst, BidirectionalBar, RadialBar, Box as ChartsBox, Stock as ChartsStock, MultiView
} from '@ant-design/charts';

export default {
  ChartsLine: Line,
  ChartsArea: Area,
  ChartsColumn: Column,
  ChartsBar: Bar,
  ChartsPie: Pie,
  ChartsDualAxes: DualAxes,
  ChartsGauge: Gauge,
  ChartsLiquid: Liquid,
  ChartsBullet: Bullet,
  ChartsScatter: Scatter,
  ChartsRose: Rose,
  ChartsOrganizationTreeGraph: OrganizationTreeGraph,
  ChartsIndentedTree: IndentedTree,
  ChartsDagreGraph: DagreGraph,
  ChartsDagreFundFlowGraph: DagreFundFlowGraph,
  ChartsSankey: Sankey,
  ChartsChord: Chord,
  ChartsHeatmap: Heatmap,
  ChartsTinyLine: TinyLine,
  ChartsTinyArea: TinyArea,
  ChartsTinyColumn: TinyColumn,
  ChartsProgress,
  ChartsRingProgress: RingProgress,
  ChartsRadar: Radar,
  ChartsTreemap: Treemap,
  ChartsFunnel: Funnel,
  ChartsWaterfall: Waterfall,
  ChartsWordCloud: WordCloud,
  ChartsHistogram: Histogram,
  ChartsSunburst: Sunburst,
  ChartsBidirectionalBar: BidirectionalBar,
  ChartsRadialBar: RadialBar,
  ChartsBox,
  ChartsStock,
  ChartsMultiView: MultiView,
};